const SelectData = {    
    organ_list: [
        'Adrenal gland',
        'Bladder',
        'Breast',
        'Epididymis',
        'Fallopian',
        'Kidney',
        'Ovary',
        'Placenta',
        'Prostate',
        'Testis',
        'Uterus',
    ],
    category_list: [
        "Aging",
        "Development",
        "Disease:Acute kidney failure-Chronic kidney disease(AKI-CKD)",
        "Disease:Benign prostatic hyperplasia(BPH)",
        "Disease:Bilateral renal cell carcinoma(RCC)",
        "Disease:Bladder cancer",
        "Disease:Breast cancer",
        "Disease:Clear cell renal cell carcinoma(ccRCC)",
        "Disease:COVID-19",
        "Disease:Diabetic kidney disease(DKD)",
        "Disease:Endometriosis",
        "Disease:High-grade serous ovarian cancer(HGSOC)",
        "Disease:Hydrosalpinx",
        "Disease:Idiopathic membranous nephropathy(IMN)",
        "Disease:IgA nephropathy",
        "Disease:Klinefelter syndrome(KS)",
        "Disease:Metastatic ovarian cancer",
        "Disease:Muscle-invasive bladder cancer(MIBC)",
        "Disease:Non-obstructive azoospermia(NOA)",
        "Disease:Prostate cancer",
        "Disease:Renal cell carcinoma",
        "Disease:Testicular cancer",
        "Disease:Transplant",
        "Disease:Triple-negative breast cancer(TNBC-BRCA1)",
        "Disease:Triple-negative breast cancer(TNBC)",
    ],
    datatype_list: [
        "2021.07.28.454201_R069",
        "PMID30429548_R062",
        "PMID31462402_R027",
        "PMID31506348_R075",
        "PMID31604275_R070",
        "PMID31896769_R016",
        "PMID32214235_R017adultadrenal-gland",
        "PMID32214235_R017adultbladder-organ",
        "PMID32214235_R017adultkidney",
        "PMID32214235_R017fetaladrenal-gland",
        "PMID32214235_R017fetalkidney",
        "PMID32214235_R017fetalovary",
        "PMID32214235_R017fetaltestis",
        "PMID32497499_R026",
        "PMID32855272_R044",
        "PMID33184181_R061adrenal-gland",
        "PMID33184181_R061kidney",
        "PMID33184181_R061placenta",
        "PMID33531352_R024",
        "PMID33763657_R073",
        "PMID33850129_R068",
        "PMID33861994_R074",
        "PMID33936064_R013",
        "PMID33950524_R031menopause",
        "PMID33950524_R031TNBC-BRCA1",
        "PMID33969332_R049",
        "PMID34038734_R037",
        "PMID34099557_R007",
        "PMID34135910_R011",
        "PMID34145246_R077development",
        "PMID34145246_R077NOA",
        "PMID34162837_R067",
        "PMID34168986_R008",
        "PMID34173975_R076",
        "PMID34385456_R023",
        "PMID34480339_R025",
        "PMID34493872_R030",
        "PMID34611125_R029",
        "PMID34626582_R042",
        "PMID34722263_R006",
        "PMID34857954_R063",
        "PMID34928497_R053",
        "PMID35320732_R059",
        "PMID35494058_R045",
        "PMID35549429_R072breast",
        "PMID35549429_R072prostate-gland",
        "PMID35657798_R010",
        "PMID35675036_R035",
        "PMID35717322_R021",
        "PMID35862581_R028",
        "PMID35864314_R047",
        "PMID36104692_R046",
        "PMID36229464_R020",
        "PMID36543131_R058Fallopian",
        "PMID36543131_R058Ovary",
    ],
    table_data: [
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        }
    ],
    columns: [
        {
          title: 'Datset ID',
          dataIndex: 'Datset ID',
          key: 'Datset ID',
          render: (text) => (<a>{text}</a>),
        },
        {
          title: 'Organ',
          dataIndex: 'Organ',
          key: 'Organ',
        },
        {
          title: 'Collection',
          dataIndex: 'Collection',
          key: 'Collection',
        },
        {
          title: 'Category',
          key: 'Category',
          dataIndex: 'Category',
        //   render: (_, { tags }) => (
        //     <>
        //       {tags.map((tag) => {
        //         let color = tag.length > 5 ? 'geekblue' : 'green';
        //         if (tag === 'loser') {
        //           color = 'volcano';
        //         }
        //         return (
        //           <Tag color={color} key={tag}>
        //             {tag.toUpperCase()}
        //           </Tag>
        //         );
        //       })}
        //     </>
        //   ),
        },
        {
            title: 'Groups',
            key: 'Groups',
          //   render: (_, record) => (
          //     <Space size="middle">
          //       <a>Invite {record.name}</a>
          //       <a>Delete</a>
          //     </Space>
          //   ),
        },
        {
            title: 'Cell Number',
            key: 'Cell Number',
        },
        {
            title: 'Data Type',
            key: 'Data Type',
        },
    ],
}

export {SelectData}