const SelectData = {    
    organ_list: [
        'Adrenal gland',
        'Bladder',
        'Breast',
        'Epididymis',
        'Fallopian',
        'Kidney',
        'Ovary',
        'Placenta',
        'Prostate',
        'Testis',
        'Uterus',
    ],
    category_list: [
        "Development",
        "Aging",
        "Disease",
    ],
    datatype_list: [
        "scRNA",
        "snRNA",
    ],
    table_data: [
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        },
        {
            'DatasetID': 'PMID32214235_R017adultadrenal-gland',
            'Organ': 'Adrenal gland',
            'Collection': 'Adrenal gland',
            'Category': 'Development',
            'Groups': '20-29',
            'Cellnumber': '15042',
            'Datatype': 'scRNA',
        }
    ],
}

export {SelectData}